name: example
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: wahwah/melon-ticket-actions
        with:
          product-id: 211212
          schedule-id: 10001
          seat-id: 1_0
          name: Send Telegram Notification
          uses: MelonKRBot/telegram-action@master
         with:
         to: ${{secrets.MelonKRBot}}
         token: ${{secrets.7855546908:AAHMBBK-eDad_sB36m5cetOjcei0Iu37408}}
        message: 'Tickets are available! Check now: https://ticket.melon.com #ticket'
